[package]
authors = ["jspspike <jspspike@gmail.com>"]
edition = "2018"
name = "snake"
version = "0.1.0"

[dependencies]
rand = "0.7.2"
sfml = "0.15.1"
indexmap = "1.3.2"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "snake"
harness = false
